// src/lib/components/Contact.svelte
<script lang="ts">
</script>

<div class="body">
	<h2>Contact</h2>
	<hr class="divider-red" />

	<div id="contact-body">
		<p>
			Need to get in touch with me for any reason? Feel free to contact me at <a
				href="mailto:cjhtsang@uwaterloo.ca"
				target="_blank"
				rel="noreferrer">cjhtsang@uwaterloo.ca</a
			> and I'll try to get back to you!
		</p>
		<div class="contact-entry">
			<a id="hi-button" href="mailto:cjhtsang@uwaterloo.ca" target="_blank" rel="noreferrer"><p>Say hi</p></a>
		</div>
	</div>
</div>

<style>
	.body {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		width: 40rem;

		text-align: center;
		margin-bottom: 5rem;
	}

	#contact-body {
		margin-top: 16px;
		width: 90%;
	}

	#hi-button {
		margin-top: 42px;

		padding-left: 1.5rem;
		padding-right: 1.5rem;
		padding-top: 0.9rem;
		padding-bottom: 0.9rem;
		text-decoration: none;
		border-width: 2px;
		border-radius: 4px;
		border-style: solid;
		border-color: var(--red-accent);
		background-color: var(--main-background);
	}

	#hi-button:hover {
		background-color: var(--navbar-hover);
	}

	.contact-entry {
		display: flex;
		flex-direction: row;
		justify-content: center;
		align-items: center;
	}
</style>

// src/components/Contact.vue
<template>
  <div id="contact" class="columns is-marginless is-centered page-item">
    <div class="column is-11">
      <article>
        <p class="title has-text-centered">
          Contact
        </p>
        <hr class="is-divider" />
        <h3 class="has-text-centered">
          Interested in getting in touch with me? Feel free to contact me with
          one of the following:
        </h3>
        <br />
        <div class="columns is-centered is-marginless is-mobile">
          <div
            class="column is-half-mobile is-marginless is-paddingless is-two-thirds-desktop"
          >
            <div class="columns is-centered is-marginless">
              <div
                class="column has-text-centered is-marginless is-paddingless"
              >
                <h3>
                  <a href="tel:+16479936280" target="_blank">
                    <font-awesome-icon
                      :icon="['fas', 'phone']"
                      size="lg"
                      fixed-width
                    />
                    +1 (647) 993-6280
                  </a>
                </h3>
              </div>
              <div
                class="column has-text-centered is-marginless is-paddingless"
              >
                <h3>
                  <a href="mailto: cjhtsang@uwaterloo.ca" target="_blank">
                    <font-awesome-icon
                      :icon="['fas', 'envelope']"
                      size="lg"
                      fixed-width
                    />
                    cjhtsang@uwaterloo.ca
                  </a>
                </h3>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
</template>

<script>
export default {
  name: "Contact"
};
</script>

<style scoped>
#contact {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: var(--main-background);
}

a {
  display: inline-block;
}

a,
a:visited {
  color: var(--text-colour);
}
a:hover {
  color: var(--url-hover);
  text-decoration: none;
}
</style>
