// src/lib/components/Projects.svelte
<script lang="ts">
	import type { ProjectInfo } from '../../types/Projects';
	import ProjectCard from './ProjectCard.svelte';

	const BOTTOM: ProjectInfo = {
		name: 'bottom',
		description: 'A cross-platform graphical process and system monitor, inspired by gotop, gtop, and htop.',
		sourceUrl: 'https://github.com/ClementTsang/bottom',
		projectUrl: 'https://clementtsang.github.io/bottom/'
	};

	const POLIFY: ProjectInfo = {
		name: 'Polify',
		description: 'Low-poly image generator library with some WebAssembly support. Written in Rust.',
		sourceUrl: 'https://github.com/ClementTsang/polify',
		projectUrl: 'https://clementtsang.github.io/polify/'
	};

	const RUSTCC: ProjectInfo = {
		name: 'rustcc',
		description: 'A simple C compiler, written in Rust.',
		sourceUrl: 'https://github.com/ClementTsang/rustcc'
	};

	const BANSHEE: ProjectInfo = {
		name: 'Banshee',
		description: 'An osu!-inspired rhythm game featuring automatic map generation based on audio, written in C++.',
		sourceUrl: 'https://github.com/ClementTsang/banshee'
	};

	const OPAL: ProjectInfo = {
		name: 'opal',
		description:
			'A static WASM website to convert between IPA and English words using a statically hosted SQLite database. Written with Rust and JavaScript.',
		sourceUrl: 'https://github.com/ClementTsang/opal',
		projectUrl: 'https://clementtsang.github.io/opal/'
	};

	const TRANSCRIPTER: ProjectInfo = {
		name: 'Transcripter',
		description:
			'A simple, offline program to automatically create transcriptions of video and audio files. Written in F#.',
		sourceUrl: 'https://github.com/ClementTsang/Transcripter'
	};

	const PROJECTS = [BOTTOM, POLIFY, RUSTCC, BANSHEE, OPAL, TRANSCRIPTER];
</script>

<div class="body">
	<h2 class="title">Projects</h2>
	<hr class="divider-red" />
	<div id="cards-section">
		{#each PROJECTS as project}
			<ProjectCard {project} />
		{/each}
	</div>
</div>

<style>
	.body {
		display: flex;
		flex-direction: column;
		justify-content: center;
		width: 90%;
	}

	.title {
		text-align: center;
	}

	#cards-section {
		margin-top: 2rem;
		display: grid;
		grid-template-columns: 1;
		grid-auto-rows: 300px;
		row-gap: 3rem;
	}

	@media screen and (min-width: 768px) {
		#cards-section {
			grid-template-columns: repeat(2, 1fr);
			column-gap: 2rem;
			grid-auto-rows: 500px;
		}
	}

	@media screen and (min-width: 1200px) {
		.body {
			width: 90%;
			max-width: 1200px;
		}
	}

	@media screen and (min-width: 1400px) {
		.body {
			width: 80%;
			max-width: 1600px;
		}
	}
</style>

// src/components/Projects.vue
<template>
  <div id="projects" class="columns is-marginless is-centered page-item">
    <div class="column is-12">
      <article>
        <p class="title has-text-centered">
          Projects
        </p>
        <hr class="is-divider" />
        <div class="columns is-centered">
          <div class="column">
            <ProjectInfo
              project-image="assets/bottom.png"
              project-link="https://github.com/ClementTsang/bottom"
              project-title="bottom"
              project-description="A crossplatform top clone, written in Rust."
            />
          </div>
          <div class="column">
            <ProjectInfo
              project-image="assets/rustnao.png"
              project-link="https://github.com/ClementTsang/RustNAO"
              project-title="RustNAO"
              project-description="A Rust wrapper for the SauceNAO API, a popular reverse image search engine."
            />
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column">
            <ProjectInfo
              project-image="assets/rustcc.png"
              project-link="https://github.com/ClementTsang/rustcc"
              project-title="rustcc"
              project-description="A simple C compiler, written from scratch in Rust."
            />
          </div>
          <div class="column">
            <ProjectInfo
              project-image="assets/banshee.png"
              project-link="https://github.com/ClementTsang/banshee"
              project-title="Banshee"
              project-description="A osu! clone, written in C++ and featuring automatic map generation."
            />
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column">
            <ProjectInfo
              project-image=""
              project-link="https://github.com/ClementTsang/dinaj_android"
              project-title="Do I Need a Jacket?"
              project-description="A simple weather app to answer a simple question."
              project-website="https://clementtsang.github.io/dinaj_android/"
            />
          </div>
          <div class="column">
            <ProjectInfo
              project-image=""
              project-link="https://github.com/ClementTsang/polify"
              project-title="Polify"
              project-description="A simple low poly art generator."
              project-website="https://clementtsang.github.io/polify/"
            />
          </div>
        </div>
      </article>
    </div>
  </div>
</template>

<script>
import ProjectInfo from "@/components/ProjectInfo";
export default {
  name: "Projects",
  components: {
    ProjectInfo
  }
};
</script>

<style scoped>
#projects {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: var(--main-background);
}

article {
  width: 90%;
  margin: 0 auto;
}
</style>
