// src/components/Experience.vue
<template>
  <div id="experience" class="columns is-marginless is-centered page-item">
    <div class="column is-11">
      <article>
        <p class="title has-text-centered">Experience</p>
        <hr class="is-divider" />
        <br />
        <p class="subtitle">Work</p>
        <WorkInfo
          entry-title="Shopify"
          :date-range="['Soon!']"
          job-position="Backend Developer Intern"
          job-description="We'll find out soon!"
          job-location="Ontario, Canada"
          job-website="https://www.shopify.ca/"
          job-website-name="Shopify"
          style="padding-bottom: 2rem"
        />
        <WorkInfo
          entry-title="Datadog"
          :date-range="['May 2021 - August 2021']"
          job-position="Software Engineering Intern - Metrics"
          job-description="Worked in the Metrics team to build an internal tool that recorded and replayed real-world loads from our services for the purposes of
          debugging and load-testing, helping speed up development time."
          job-location="New York, United States"
          job-website="https://www.datadoghq.com/"
          job-website-name="Datadog"
          style="padding-bottom: 2rem"
        />
        <WorkInfo
          entry-title="Wish"
          :date-range="['Jan 2020 - Apr 2020', 'Sept 2020 - Dec 2020']"
          job-position="Software Engineering Intern"
          job-description="Worked on the Wish Marketplace team as a mobile and backend developer for the Wish Local app, introducing new features and fixing bugs."
          job-location="Ontario, Canada"
          job-website="https://www.wish.com/companyinfo"
          job-website-name="Wish"
          style="padding-bottom: 2rem"
        />
        <WorkInfo
          entry-title="YuJa"
          :date-range="['May 2019 - Aug 2019']"
          job-position="Software Developer - Full Stack"
          job-description="Worked as a full stack software developer
									for a new product, Panorama, automatically creating 
									accessible documents for files uploaded to LMS sites like D2L and Blackboard."
          job-location="Ontario, Canada"
          job-website="https://www.yuja.com/"
          job-website-name="YuJa"
          style="padding-bottom: 2rem"
        />
        <WorkInfo
          entry-title="YuJa"
          :date-range="['Sept 2018 - Dec 2018']"
          job-position="Software Developer - Testing and Operations"
          job-description="Ran QA tests to ensure the quality of our product and
        new features without any regressions, in addition to developing
        automated tests to save time and improve test quality using Selenium."
          job-location="Ontario, Canada"
          job-website="https://www.yuja.com/"
          job-website-name="YuJa"
          style="padding-bottom: 2rem"
        />
        <hr class="is-thin-divider" />
        <br />
        <p class="subtitle">Education</p>
        <WorkInfo
          entry-title="University of Waterloo"
          :date-range="['2017 - Present']"
          job-position="Computer Science, Honours"
          job-description="Currently a fourth year Computer Science student at the Unviersity of Waterloo. Set to graduate in April 2022!"
          job-location="Ontario, Canada"
          job-website="https://uwaterloo.ca/"
          job-website-name="University of Waterloo"
          style="padding-bottom: 2rem"
        />
      </article>
    </div>
  </div>
</template>

<script>
import WorkInfo from "@/components/WorkInfo";
export default {
  name: "Experience",
  components: {
    WorkInfo,
  },
};
</script>

<style scoped>
#experience {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: var(--main-background);
}
</style>

// src/lib/components/Experience.svelte
<script lang="ts">
	import ExperienceCard from './ExperienceCard.svelte';
	import type { Experience } from '../../types/Experience';

	const DATADOG: Experience = {
		name: 'Datadog',
		dates: ['August 2022 - Present'],
		location: 'New York, United States',
		link: { name: 'Datadog', url: 'https://www.datadoghq.com/' },
		position: 'Software Engineer - Metrics',
		description: 'Currently work as a software engineer regarding the storage of timeseries data.'
	};

	const SHOPIFY: Experience = {
		name: 'Shopify',
		dates: ['Sept 2021 - Dec 2021 '],
		location: 'Ontario, Canada',
		link: { name: 'Shopify', url: 'https://www.shopify.ca/' },
		position: 'Backend Developer Intern ',
		description:
			'Worked as a backend developer at Shopify on the Commerce Trust and Integrity team to improve analyst tools and the quality of fraud detection.'
	};

	const DATADOG_INTERN: Experience = {
		name: 'Datadog',
		dates: ['May 2021 - Aug 2021'],
		location: 'New York, United States',
		link: { name: 'Datadog', url: 'https://www.datadoghq.com/' },
		position: 'Software Engineering Intern - Metrics',
		description:
			'Worked in the Metrics team to build an internal tool that recorded and replayed real-world loads from our services for the purposes of debugging and load-testing, helping speed up development time.'
	};

	const WISH: Experience = {
		name: 'Wish',
		dates: ['Jan 2020 - Apr 2020', 'Sept 2020 - Dec 2020'],
		location: 'Ontario, Canada',
		link: { name: 'Wish', url: 'https://www.wish.com/companyinfo' },
		position: 'Software Engineering Intern',
		description:
			'Worked on the Wish Marketplace team as a mobile and backend developer for the Wish Local app, introducing new features and fixing bugs.'
	};

	const YUJA_FULL_STACK: Experience = {
		name: 'YuJa',
		dates: ['May 2019 - Aug 2019'],
		location: 'Ontario, Canada',
		link: { name: 'YuJa', url: 'https://www.yuja.com/' },
		position: 'Software Developer - Full Stack',
		description:
			'Worked as a full stack software developer for a new product, Panorama, automatically creating accessible documents for files uploaded to LMS sites like D2L and Blackboard.'
	};

	const YUJA_QA: Experience = {
		name: 'YuJa',
		dates: ['Sept 2018 - Dec 2018'],
		location: 'Ontario, Canada',
		link: { name: 'YuJa', url: 'https://www.yuja.com/' },
		position: 'Software Developer - Testing and Operations',
		description:
			'Ran QA tests to ensure the quality of our product and new features without any regressions, in addition to developing automated tests to save time and improve test quality using Selenium.'
	};

	let workExperiences: Experience[] = [DATADOG, SHOPIFY, DATADOG_INTERN, WISH, YUJA_FULL_STACK, YUJA_QA];

	const SCHOOL: Experience = {
		name: 'University of Waterloo',
		dates: ['2017 - 2022'],
		location: 'Ontario, Canada',
		link: { name: 'University of Waterloo', url: 'https://uwaterloo.ca/' },
		position: 'Bachelor of Computer Science',
		description: 'Studied and graduated from the University of Waterloo with distinction.'
	};
</script>

<div id="experience" class="section">
	<div class="body">
		<h2 class="title">Experience</h2>
		<hr class="divider-red" />

		<h3>Work</h3>
		<div class="card-wrapper">
			{#each workExperiences as exp}
				<ExperienceCard {exp} />
			{/each}
		</div>

		<hr class="divider-red" />

		<h3>Education</h3>
		<div class="card-wrapper">
			<ExperienceCard exp={SCHOOL} />
		</div>
	</div>
</div>

<style>
	.title {
		text-align: center;
	}

	.body {
		display: flex;
		flex-direction: column;
		justify-content: center;
		width: 90%;
	}

	@media screen and (min-width: 1200px) {
		.body {
			width: 70%;
			max-width: 1080px;
		}
	}

	@media screen and (min-width: 1400px) {
		.body {
			width: 60%;
			max-width: 1080px;
		}
	}

	.card-wrapper {
		display: flex;
		flex-direction: column;
		row-gap: 2rem;
	}
</style>
